dist: trusty
sudo: false
language: csharp
mono: none
dotnet: 3.1.100
install:
  - dotnet restore
script:    
  - dotnet test
after_success:
  - echo dotnet test  succeeded
after_failure:
  - echo dotnet test  failed