name: publish
on: 
  push
    branches:
      - master
    paths:
      - src/*

jobs:
  publish:
    name: publish project
    runs_on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up dotnetcore
        uses: actions/setup-dotnet@v1
        with:
          - dotnet-version: 3.1.100
      - name: publish project
      - run: dotnet publish -c release

  