name: test
on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Publish project
<<<<<<< HEAD
      run: dotnet test  ../framework/Galo.Apsk.sln
=======
      run: dotnet test  ./framework/Galo.Apsk.sln
>>>>>>> 918dc80479cdab2709cd4b230822671c766274bc
